### ISSUE TITLE
[gm45-thinkpad] BLC_PWM_CTL is hard-coded

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#10]
The PWM frequency of the inverters on GM45 ThinkPads is hard-coded to a value that's pretty much always wrong.

CCFL's and LED's need completely different values, and even different screen types often differ slightly.

**Comment by ghost** [comment]
This can be solved either by reading a value from cbfs (which requires user testing / input for their particular screen), or by maintaining a whitelist of known-good values based on EDID's.

**Comment by ghost** [comment]
https://github.com/librecore-org/librecore/wiki/ThinkPad-backlight-values

**Comment by zamaudio** [comment]
Can we write some logic into coreboot that chooses an appropriate backlight value based on EDID?

**Comment by ArthurHeymans** [comment]
Yes there is already an edid display string parser, we just need to hook it up to the edid struct and have a array of structs containing display strings and a good BLC_PWM_CTL value.

**Comment by zamaudio** [comment]
Sounds good, we might be able to do a rough matching based on a subset of EDID fields?  Let's go for it

**Comment by zamaudio** [comment]
Something like:
```
switch(edid_blc_type) {
  case KNOWN_MODEL:
    BLC = blc_value(KNOWN_MODEL); break;
  case UNKNOWN_CCFL:
    BLC = blc_value(BLC_CCFL_DEFAULT); break;
  case UNKNOWN_LED:
    BLC = blc_value(BLC_LED_DEFAULT); break;
}
```

**Comment by ArthurHeymans** [comment]
Sadly it's not possible to know from edid which backlight type it has. So the only option is to have a list with edid strings (see wiki) with a good value or 1 default. This makes having an exhaustive list important...

**Comment by zamaudio** [comment]
Here's a summary list of what we have so far, according to the [wiki](https://github.com/librecore-org/librecore/wiki/ThinkPad-backlight-values) (update this post)
```
'B121EW03 V3 ' LED 0x16011601
'B121EW03 V6 ' CCFL 0x80018001
'B121EW09 V2 ' LED 0x16011601
'B121EW09 V3 ' LED 0x16011601
'B141EW04' CCFL 0x60016001
'HV121WX4-100' CCFL 0x60016001
'HV121WX4-110' CCFL 0x60016001
'HV121WX4-120' CCFL 0x60016001
'LP121WX3-TLA1' LED 0X16011601
'LP121WX3-TLC1' LED 0x16011601
'LP141WX3' CCFL 0x60016001
'LP141WX5' LED 0x16011601
'LP154W02' CCFL 0x60016001
'LTD121EWVB' CCFL 0x60016001
'LTN121AP02001' CCFL 0x60016001
'LTN121AT03001' CCFL 0x60016001
'LTN141AT12' LED 0x06100610
'LTN141W1-L05' CCFL 0x60016001
'LTN141WD-L05' CCFL 0x60016001
'LTN154P3-L02' CCFL 0x60016001
'N121IB-L05' LED 0x16011601
```

**Comment by ghost** [comment]
I think it's safe to say that `0x16011601` is a good value for nearly all LED screens, and `0x60016001` is a good value for nearly all CCFL screens.

The only deviations from this would be `B121EW03 V6` and `LTN141AT12`. I'm 100% sure about the first not working well with `0x60016001` (high-pitched noise), but I could re-test the latter with `0x16011601`. I may have been wrong.

**Comment by ArthurHeymans** [comment]
So the formula for going from BLC_PWM_CTL[31:16] (4 numbers most to the left in hex) to pwm freq is

"f_pwm = 200 * 10^6 / (128 * BLC_PWM_CTL[31:16])"

So 
* 0x6000 -> 63Hz
* 0x1600 -> 277Hz

Some datasheets (mostly LED) have a range in which f_pwm must lie and sometimes even an ideal value.
I think LED in general needs to be 200-1000Hz and CCFL 50-200Hz. I'd say the higher the better...

**Comment by ArthurHeymans** [comment]
List with all possible displays I could find that gm45 thinkpads could have: https://pad.riseup.net/p/gm45_display_inverter

**Comment by zamaudio** [comment]
Ok, how can we populate that table more so there are no NA's

**Comment by ArthurHeymans** [comment]
NA often means that datasheets don't specify it. I think when submitting this large struct with display strings and pwm freq values, there should be comments next to each display saying how it was obtained. That way if people encounter problems the code can tell them it was only our best guess.

**Comment by ArthurHeymans** [comment]
Apparently the core display clock is not 200MHz but 333MHz, this means that 0x6000 divisor is not 63Hz but 105Hz, which seems more likely.

**Comment by ghost** [comment]
Related: https://review.coreboot.org/#/c/17597/

**Comment by ghost** [comment]
https://review.coreboot.org/#/q/topic:gm45_backlight

Whitelist of tested values per EDID merged in coreboot master.
