### ISSUE TITLE
[ga-945gcm-s2l] Occasional black (green-ish) screen after KMS

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#12]
Sometimes, when one would expect a login screen, the display remains black (with a green-ish tone). This happens after the kernel sets mode. SeaBIOS does give normal output when this happens.

Short-pressing the power button will shut down the system, so it isn't locked up.

This could well be related to #7, or maybe to the GPU being clocked lower than normal. Or maybe both. I have been able to trigger this issue both with PC2-6400 DIMM's and PC2-5300 DIMM's.

**Comment by ghost** [comment]
Serial console shows this:

> [    8.703161] fbcon: inteldrmfb (fb0) is primary device
> [    8.703384] Console: switching to colour frame buffer device 240x67
> [    8.714936] i915 0000:00:02.0: fb0: inteldrmfb frame buffer device
> [   11.502693] random: crng init done
> [   13.381436] [drm:i915_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun

**Comment by the-hollow-man** [comment]
After flashing the latest test ROM, I have no longer seen this issue on any of my 4 ga-945gcm-s2l boards. I'm assuming this fixed it.

**Comment by the-hollow-man** [comment]
I still get this with KVR800 kits, unfortunately.

**Comment by ghost** [comment]
So far, I am only able to trigger this on Debian testing. It never happens on Debian stable.
Also, moving the mouse cursor vigorously seems to get rid of the green screen and show GDM.

This may also be a GMA950 bug in Linux 4.8, perhaps not coreboot-related.
