### ISSUE TITLE
[gm45] Fix FSB 800MHz

### ISSUE THREAD

**Issue by ArthurHeymans** [librecore-org/librecore#14]
800MHz fsb does not work on gm45, which causes SU (ultra low voltage?) CPU on x200s and x200t to not boot. Fixing this would also allow the (very high end) thinkpad x301 to be ported, which exclusively uses SU CPUs.

A possible test setup for this would be a lenovo T400, fix the dock code so that the SIO can be used / just use EHCI debug. Find a crappy cheap 800MHz fsb CPU that fits the socket and do the usual raminit debugging.
Fixing the dock would be more interesting since this would allow to use SerialICE.

**Comment by ghost** [comment]
I have all these things:

- T400's
- Advanced mini docks
- T7300 cpu

**Comment by ghost** [comment]
If we fix the dock, I can do all the required testing. And we'd have a working dock, which would also be very nice.

Tracked in issue #15.

**Comment by ArthurHeymans** [comment]
Not a problem apparently.
