### ISSUE TITLE
[945gc] Resume from suspend is broken

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#17]
When suspending a 945GC board, all goes well. But resuming results in a double reset followed by a cold boot, which may or may not hang.

It would be nice if we could either fix this, or avoid suspend from being used in the first place (tell the kernel S3 is unsupported).

**Comment by ArthurHeymans** [comment]
on 945gc (works on 945gm) suspend is actually implemented but resume does not work.
Note that on pineview and x4x resume is not implemented and will probably result in same behavior.

**Comment by ArthurHeymans** [comment]
Fixed for ga-945gcm-s2l: https://review.coreboot.org/#/c/17617/
Intel d945gclf does not work resets twice.

**Comment by ArthurHeymans** [comment]
Works on d945gclf https://review.coreboot.org/#/c/17996/ . Same fix does not works for P5GC-MX so I think it will require some deeper fixes.

**Comment by ghost** [comment]
Tested on ga-945gcm-s2l: working without issues.

Tested on d945gclf: working, but shows an error upon every resume:

```
[  242.240053] pciehp 0000:00:1c.0:pcie004: Timeout on hotplug command 0x1038 (issued 146392 msec ago)
[  242.340090] pciehp 0000:00:1c.0:pcie004: Device 0000:01:00.0 already exists at 0000:01:00, cannot hot-add
[  242.340097] pciehp 0000:00:1c.0:pcie004: Cannot add device at 0000:01:00
[  242.448109] pciehp 0000:00:1c.0:pcie004: Device 0000:01:00.0 already exists at 0000:01:00, cannot hot-add
[  242.448115] pciehp 0000:00:1c.0:pcie004: Cannot add device at 0000:01:00
[  242.448164] pcieport 0000:00:1c.0: System wakeup disabled by ACPI
```

It does not seem to have adverse effects so far though.

**Comment by ArthurHeymans** [comment]
happens on x60 too (device 00:1c.0)
