### ISSUE TITLE
[x4x] Implement S3

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#18]
According to @ArthurHeymans in issue #17, unlike 945gc (where it doesn't work), resume from S3 isn't implemented at all on x4x. We should try to get this to work eventually.

**Comment by ArthurHeymans** [comment]
done https://review.coreboot.org/#/c/17998/ :)

**Comment by ghost** [comment]
Tested and working.

**Comment by zamaudio** [comment]
Good job!
