### ISSUE TITLE
[gm45] T400/T500/W500 with hybrid graphics won't display anything (ever)

### ISSUE THREAD

**Issue by ArthurHeymans** [librecore-org/librecore#19]
A hybrid driver was merged to handle all Lenovo laptops with hybrid graphics, but it fails to configure the display mux correctly on gm45 laptops with hybrid graphics. https://review.coreboot.org/12896

The results is that neither in coreboot/payload, nor in Linux the display works. This a potential fix but I can't test it due to the lack of actual hardware: https://review.coreboot.org/16354. (Hardware needs to have an Ati card)

**Comment by ghost** [comment]
Seems to be fixed upstream: https://review.coreboot.org/#/c/18010/
