### ISSUE TITLE
[ga-945gcm-s2l] Some 800MHz DIMM's are unstable

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#7]
Tested primarily with different Kingston ValueRAM (KVR800) DIMM's.

Sometimes the board locks up with artifacts all over the screen, so it's probably video RAM / raminit related. This does not seem to happen with 667MHz Micron modules.

Memtest86+ does not show any errors with the KVR800 DIMM's. There is also no useable debug output when the system locks up. This bug is quite hard to trigger.

**Comment by ghost** [comment]
Some 800MHz Kingston ValueRAM kits won't boot at all on the ga-945gcm-s2l (black screen, not passing ramstage), while they work fine on the ga-g41m-es2l and the d945gclf.

**Comment by zamaudio** [comment]
Sounds like i945 raminit has issues, I won't be fixing it.

**Comment by ArthurHeymans** [comment]
Raminit was initially only written for 533MHz fsb on 945gc (atom cpu), I somewhat fixed it for 800MHz and 1067MHz fsb but some work might still be needed.

**Comment by ghost** [comment]
Sometimes, this happens during boot, triggering a reboot:

```
Begin: Loading essential drivers ... done.
Begi[    2.997655] PM: Starting manual resume from disk
n: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
[    3.048055] usb 4-1: new full-speed USB device number 2 using uhci_hcd

coreboot-4.5-394-g619a245 Thu Nov 24 20:39:41 UTC 2016 romstage starting...
soft reset detected.
```

After which SeaBIOS hangs on "Press ESC for boot menu."

**Comment by ghost** [comment]
coreboot log: https://quietlife.nl/files/ga-945gcm-s2l/log/ramfail/log2.txt

I also noticed that this problem can occur with both one DIMM / single channel and two DIMM's / dual channel. It can also happen both on FSB800 (E4600) and FSB1066 (E7500).

**Comment by ArthurHeymans** [comment]
I had this too previously but but latest roms should have fix. Do you still have this issue now?

**Comment by ghost** [comment]
The most recent ROM I tested was the 'superiotest' ROM dated November 24th. This still had this issue from time to time, but certainly not all the time.

**Comment by ghost** [comment]
With the latest test ROM's, I have no longer encountered any issues with KVR800 RAM on any of my 4 boards.
