### ISSUE TITLE
[rtl8168] MAC address is hard-coded / generic

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#8]
Tested on both the ga-g41m-es2l and the ga-945gcm-s2l.

If I understand correctly, these NIC's have to be reset, which hard-codes a MAC address. This is not really ideal. Although the workaround is relatively easy ('spoof' the real MAC), it would be nice if this would just work.

**Comment by ArthurHeymans** [comment]
maybe reset only is enough on ga-945gcm-s2l and spoofing of mac is not required. Further investigation is needed.

I think the best way to implement this is have a function in coreboot to be able to load an int from cbfs and then use that as macaddress, while stil having a default value in case of absence.

**Comment by zamaudio** [comment]
MAC addresses are 6 bytes.. you can't load that into an int.  But you could load it as text field and have it parsed from cbfs?

**Comment by zamaudio** [comment]
https://github.com/coreboot/coreboot/blob/master/src/mainboard/google/beltino/lan.c looks like google already did this kind of thing for a chromeos board.  We need to test this sequence of code on our boards since its the same pci id 10ec:8168.  If it works, we should integrate something like this into our PCI driver.

**Comment by ghost** [comment]
https://review.coreboot.org/#/c/17672/

**Comment by zamaudio** [comment]
Can someone test the above patch please before it gets merged... ^

**Comment by ghost** [comment]
Tested on two ga-g41m-es2l's: working perfectly.

Tested on two ga-945gcm-s2l's: working perfectly.

**Comment by zamaudio** [comment]
Sweet thanks!
