### ISSUE TITLE
[x4x] All RAM is downclocked to 667MHz with FSB1333

### ISSUE THREAD

**Issue by ghost** [librecore-org/librecore#9]
Regardless of the DIMM (i.e. even with PC2-6400 or PC2-8500 modules), the RAM frequency never exceeds 667MHz. Up to 800MHz should be supported, as is printed on the board.

**Comment by zamaudio** [comment]
What CPU is that? I had to downclock the RAM from 800->667 for FSB1333 cpus due to some bug in raminit.

**Comment by ghost** [comment]
It's with all FSB1333 cpu's. I never tested FSB1066 chips on this board.

Does 800MHz RAM work with FSB1066?

**Comment by zamaudio** [comment]
I know 800MHz RAM works with FSB800, not sure about FSB1066

**Comment by ArthurHeymans** [comment]
FSB1066 is very broken. It does not accept ram in the second slot.

**Comment by zamaudio** [comment]
Maybe it's related to this? https://review.coreboot.org/#/c/17587 someone ought to check this out and test it, I don't have flash tools here right now

**Comment by ghost** [comment]
This patch made no difference, unfortunately.

**Comment by ArthurHeymans** [comment]
https://review.coreboot.org/#/c/18022/
Fixes all issues with 1333MHz (limited to 667MHz) and 1067MHz (wont boot with dimm in second slot).
800MHz still works fine.

**Comment by ghost** [comment]
Tested DDR2-800 with FSB1333 and it's indeed working fine. Memtest86+ passes multiple times without errors and stressing the system is completely stable for hours.
